export { sessions, users } from "@/modules/auth/db/schema";
export {
  hashPassword,
  isValidEmail,
  loginUser,
  type LoginUserResult,
  type CurrentUser,
  MIN_PASSWORD_LENGTH,
  normalizeEmail,
  registerUser,
  logoutUser,
  AUTH_SESSION_COOKIE_NAME,
  clearSessionCookie,
  createSession,
  deleteSession,
  getCurrentSession,
  getCurrentSessionToken,
  getCurrentUser,
  requireCurrentUser,
  setSessionCookie,
  validateLoginUserInput,
  validateRegisterUserInput,
  verifyPassword,
} from "@/modules/auth/server";
